import {
  Baby,
  Banknote,
  Beer,
  Bike,
  Book,
  Briefcase,
  Bus,
  Candy,
  Car,
  CircleHelp,
  Coffee,
  CreditCard,
  Dumbbell,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HandCoins,
  Heart,
  Home,
  Music,
  PawPrint,
  PiggyBank,
  Pill,
  Plane,
  Receipt,
  Scissors,
  Shirt,
  ShoppingCart,
  Smartphone,
  Star,
  Tag,
  Ticket,
  TrendingUp,
  Trophy,
  Users,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

// Category.icon stores one of these keys.
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  tag: Tag,
  cart: ShoppingCart,
  food: Utensils,
  coffee: Coffee,
  candy: Candy,
  beer: Beer,
  car: Car,
  bus: Bus,
  bike: Bike,
  fuel: Fuel,
  plane: Plane,
  home: Home,
  power: Zap,
  wifi: Wifi,
  phone: Smartphone,
  clothes: Shirt,
  haircut: Scissors,
  repair: Wrench,
  health: Pill,
  fitness: Dumbbell,
  pet: PawPrint,
  baby: Baby,
  gift: Gift,
  heart: Heart,
  film: Film,
  music: Music,
  game: Gamepad2,
  ticket: Ticket,
  book: Book,
  education: GraduationCap,
  trophy: Trophy,
  star: Star,
  people: Users,
  work: Briefcase,
  cash: Banknote,
  coins: HandCoins,
  card: CreditCard,
  wallet: Wallet,
  savings: PiggyBank,
  invest: TrendingUp,
  receipt: Receipt,
};

export const CATEGORY_COLORS = [
  '#ef4444',
  '#f97316',
  '#f59e0b',
  '#84cc16',
  '#10b981',
  '#14b8a6',
  '#0ea5e9',
  '#3b82f6',
  '#6366f1',
  '#8b5cf6',
  '#d946ef',
  '#ec4899',
  '#78716c',
  '#64748b',
];

export const UNCATEGORISED = { id: 'none', name: 'Ukategoriseret', color: '#94a3b8', icon: 'unknown' };

export function categoryIcon(icon: string | undefined): LucideIcon {
  return (icon && CATEGORY_ICONS[icon]) || CircleHelp;
}
